---
- name: ROKS - Init cluster state
  ansible.builtin.set_fact:
    cl_exists: false

- name: ROKS - Check cluster existence
  ansible.builtin.command:
    cmd: "{{ ibmcloud }} ks cluster ls --provider vpc-gen2 --json"
  register: ibm_cl
  changed_when: false

- name: ROKS - Set of cluster exists
  ansible.builtin.set_fact:
    cl_exists: true
  when: (ibm_cl.stdout | from_json) | selectattr('name', 'equalto', item.name) | map(attribute='name')
