namespace: stolostron
name: rhacm
version: 0.0.3

description: Red Hat Advanced Cluster Management environment deployment automation
readme: README.md
license_file: 'LICENSE'
homepage: https://github.com/stolostron/ansible-collection.rhacm
repository: https://github.com/stolostron/ansible-collection.rhacm
documentation: https://github.com/stolostron/ansible-collection.rhacm/docs
issues: https://github.com/stolostron/ansible-collection.rhacm/issues

authors:
  - maxbab (https://github.com/MaxBab)

tags: [
  'acm',
  'rhacm',
  'multicluster',
  'advanced-cluster-management',
  'management',
  'openshift',
  'kubernetes'
]

dependencies:
  kubernetes.core: '==2.4.0'
  community.okd: '==2.3.0'
  azure.azcollection: '==1.16.0'
