---
- name: ARO - Get subscription details
  ansible.builtin.set_fact:
    subscription: "{{ managed_openshift_clusters_credentials
      | selectattr('name', 'equalto', item.credentials) | first }}"

- name: ARO - Create platform credentials directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.azure"
    mode: 0755
    state: directory

- name: ARO - Create account credentials file
  ansible.builtin.blockinfile:
    path: "{{ lookup('env', 'HOME') }}/.azure/credentials"
    block: "{{ lookup('ansible.builtin.template', 'cloud-creds.j2') }}"
    marker: "#{mark} rhacm-automation"
    create: true
    state: present
