---
- name: ARO - Create AD application
  ansible.builtin.include_tasks:
    file: rbac_app_and_sp.yml

- name: ARO - Recheck the AD app if was created
  azure.azcollection.azure_rm_adapplication_info:
    profile: rhacm-automation
    tenant: "{{ subscription.tenant_id }}"
  register: ad_app
  no_log: true

- name: ARO - Fetch app and object id from the AD app
  ansible.builtin.set_fact:
    app_id: "{{ ad_app.applications
      | selectattr('app_display_name', 'match', app_display_name)
      | map(attribute='app_id') | first }}"
    object_id: "{{ ad_app.applications
      | selectattr('app_display_name', 'match', app_display_name)
      | map(attribute='object_id') | first }}"

- name: ARO - Create AD Service Principal
  azure.azcollection.azure_rm_adserviceprincipal:
    profile: rhacm-automation
    tenant: "{{ subscription.tenant_id }}"
    app_id: "{{ app_id }}"
    state: present
  register: sp_created

- name: ARO - Wait to sync the AD app with the new Service Principal
  ansible.builtin.pause:
    minutes: 1
  when:
    - sp_created.changed
    - sp_created.object_id

- name: ARO - Fetch the AD Service Principal info
  azure.azcollection.azure_rm_adserviceprincipal_info:
    profile: rhacm-automation
    tenant: "{{ subscription.tenant_id }}"
    app_id: "{{ app_id }}"
  register: ad_sp

- name: ARO - Fetch the object id of the AD Service Principal
  ansible.builtin.set_fact:
    sp_object_id: "{{ ad_sp.service_principals[0].object_id }}"

- name: ARO - Set AD app password
  azure.azcollection.azure_rm_adpassword:
    profile: rhacm-automation
    tenant: "{{ subscription.tenant_id }}"
    app_id: "{{ app_id }}"
    value: "{{ subscription.client_secret }}"
    state: present
  no_log: true

- name: ARO - Fetch ARO Resource Group Contributor Role Definition Scope
  azure.azcollection.azure_rm_roledefinition_info:
    profile: rhacm-automation
    scope: "/subscriptions/{{ subscription.subscription_id }}"
  register: rg_contrib_role_scope
  no_log: true

- name: ARO - Set Object ID of Contributor Role Definition
  ansible.builtin.set_fact:
    rg_contrib_object_id: "{{ rg_contrib_role_scope.roledefinitions
      | selectattr('role_name', 'match', 'Contributor')
      | map(attribute='id') | first }}"
  no_log: true

- name: ARO - Set ARO Subscription Contributor Role to the Service Principal
  azure.azcollection.azure_rm_roleassignment:
    profile: rhacm-automation
    subscription_id: "{{ subscription.subscription_id }}"
    tenant: "{{ subscription.tenant_id }}"
    scope: "/subscriptions/{{ subscription.subscription_id }}"
    assignee_object_id: "{{ sp_object_id }}"
    role_definition_id: "{{ rg_contrib_object_id }}"

- name: ARO - Fetch ARO Resource Group Network Contributor Role Definition Scope
  azure.azcollection.azure_rm_roledefinition_info:
    profile: rhacm-automation
    scope: "/subscriptions/{{ subscription.subscription_id }}/resourceGroups/{{ item.name }}-rg"
  register: rg_net_contrib_role_scope
  no_log: true

- name: ARO - Set Object ID of Network Contributor Role Definition
  ansible.builtin.set_fact:
    rg_net_contrib_object_id: "{{ rg_net_contrib_role_scope.roledefinitions
      | selectattr('role_name', 'match', 'Network Contributor')
      | map(attribute='id') | first }}"
  no_log: true

# Uses local module. Remove when merged:
# https://github.com/ansible-collections/azure/pull/901
- name: ARO - Fetch AD Service Principal info
  azure_rm_adserviceprincipal_info:
    profile: rhacm-automation
    tenant: "{{ subscription.tenant_id }}"
    app_display_name: "Azure Red Hat OpenShift RP"
  register: aro_ad_sp

- name: ARO - Set Service Principal Object ID
  ansible.builtin.set_fact:
    aro_sp_object_id: "{{ aro_ad_sp.service_principals[0].object_id }}"

- name: ARO - Granting Resource Provider Contributor access to the ARO virtual network
  azure.azcollection.azure_rm_roleassignment:
    profile: rhacm-automation
    scope: "/subscriptions/{{ subscription.subscription_id }}/resourceGroups/\
            {{ item.name }}-rg/providers/Microsoft.Network/virtualNetworks/{{ item.name }}-vnet"
    assignee_object_id: "{{ aro_sp_object_id }}"
    role_definition_id: "{{ rg_net_contrib_object_id }}"
