---
- name: Create managed openshift working directory
  ansible.builtin.file:
    path: "{{ working_path }}"
    state: directory
    recurse: true
  when: state == "present"

- name: Managed OCP directory for each cluster - {{ state }}
  vars:
    state_step: "{%- if state == 'present' -%}
                 directory
                 {%- elif state == 'absent' -%}
                 absent
                 {%- endif -%}"
  ansible.builtin.file: # noqa: jinja[spacing]
    path: "{{ working_path }}/{{ item.name }}"
    mode: '0755'
    state: "{{ state_step }}"
  loop: "{{ clusters_list }}"

- name: Cleanup clusters entries
  when: state == "absent"
  block:
    - name: Remove clusters details from the state file
      ansible.builtin.blockinfile:
        path: "{{ cl_details_file_path }}"
        block: ""
        marker: "#{mark} {{ item.name }} details"
        state: absent
      loop: "{{ clusters_list }}"

    - name: Check the file "{{ clusters_details_file }}"
      ansible.builtin.stat:
        path: "{{ cl_details_file_path }}"
      register: cl_file_state

    - name: Delete the file if empty - "{{ clusters_details_file }}"
      ansible.builtin.file:
        path: "{{ cl_details_file_path }}"
        state: absent
      when:
        - cl_file_state.stat.exists
        - cl_file_state.stat.size == 0
