---
- name: Sets credentails filename and path
  ansible.builtin.set_fact:
    creds_path: "{%- if item.cloud.platform == 'aws' or item.cloud.platform == 'gcp' -%}
                 {{ item.cloud.platform }}
                 {%- elif item.cloud.platform == 'openstack' -%}
                 config/openstack
                 {%- endif -%}"
    creds_file: "{%- if item.cloud.platform == 'aws' -%}
                 credentials
                 {%- elif item.cloud.platform == 'gcp' -%}
                 osServiceAccount.json
                 {%- elif item.cloud.platform == 'openstack' -%}
                 clouds.yaml
                 {%- endif -%}"

- name: Verify openshift cloud credentials
  ansible.builtin.stat:
    path: "{{ lookup('env', 'HOME') }}/{{ creds_path }}/{{ creds_file }}"
  register: cloud_creds

- block:
    - name: Create platform creds directory
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/.{{ creds_path }}"
        mode: 0755
        state: directory

    - name: Create cloud credentials file
      ansible.builtin.template:
        src: cloud-creds.j2
        dest: "{{ lookup('env', 'HOME') }}/.{{ creds_path }}/{{ creds_file }}"
        mode: 0600
  when: not cloud_creds.stat.exists
