---
- name: Sets credentails filename and path
  ansible.builtin.set_fact:
    creds_path: "{%- if item.cloud.platform == 'aws' or item.cloud.platform == 'gcp' -%}
                 {{ item.cloud.platform }}
                 {%- elif item.cloud.platform == 'openstack' -%}
                 config/openstack
                 {%- endif -%}"
    creds_file: "{%- if item.cloud.platform == 'aws' -%}
                 credentials
                 {%- elif item.cloud.platform == 'gcp' -%}
                 gcp-service-account-rhacm-automation.json
                 {%- elif item.cloud.platform == 'openstack' -%}
                 clouds.yaml
                 {%- endif -%}"

- name: Create platform creds directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.{{ creds_path }}"
    mode: 0755
    state: directory

- name: Create cloud credentials file for GCP cloud
  ansible.builtin.template:
    src: cloud-creds.j2
    dest: "{{ lookup('env', 'HOME') }}/.{{ creds_path }}/{{ creds_file }}"
    mode: 0600
  when: item.cloud.platform == 'gcp'

- name: Create cloud credentials file
  ansible.builtin.blockinfile:
    block: "{{ lookup('ansible.builtin.template', 'cloud-creds.j2') }}"
    path: "{{ lookup('env', 'HOME') }}/.{{ creds_path }}/{{ creds_file }}"
    create: yes
    mode: 0600
  when: item.cloud.platform != 'gcp'
