---
state: present

# OpenShift pull secret
pull_secret:

# For other managed openshift clusters platforms,
# refer to role doc and config-sample.yml file.
# managed_openshift_clusters:
#   - name: cluster-rosa
#     platform: rosa
#     credentials: rosa-creds
#     region: us-east-2
#     network:
#       cluster: 10.128.0.0/14
#       machine: 10.0.0.0/16
#       service: 172.30.0.0/16
#     machines:
#       worker:
#         type: m5.xlarge
#         count: 3
#     openshift_version: "4.15"

managed_openshift_clusters_credentials:
  - name: rosa-creds
    aws_access_key_id: <your_key>
    aws_secret_access_key: <your_secret_key>
    rosa_token: <your_rosa_token>
