---
# curl -s -X GET https://quay.io/api/v1/repository/openshift-release-dev/ocp-release/tag/?filter_tag_name=like:4.9 \
# | jq -S '.tags[] | {name: .name} | select(.name | endswith("x86_64"))' | jq -r '.name'
- name: Fetch hive cluster image if not provided manually
  ansible.builtin.uri:
    url: "{{ ocp_image_query_url }}/?filter_tag_name=like:{{ item.hive_cluster_version }}"
    method: "GET"
    status_code: 200
  register: img
  when: item.hive_cluster_image is not defined

- name: Select latest hive cluster image according to provided version
  ansible.builtin.set_fact:
    hive_cluster_ver: "{{ img.json.tags
      | selectattr('name', 'match', item.hive_cluster_version + '.*' + cluster_architecture | string)
      | map(attribute='name') | first }}"
  when: item.hive_cluster_image is not defined

- name: Build acm hive cluster version url string
  ansible.builtin.set_fact:
    hive_cluster_image: "{{ ocp_image_base_url }}:{{ hive_cluster_ver }}"
  when: item.hive_cluster_image is not defined

- name: Cluster Deployment for cluster "{{ item.name }}"
  community.okd.k8s:
    host: "{{ cluster_api }}"
    api_key: "{{ cluster_api_token }}"
    validate_certs: false
    definition: "{{ lookup('template', 'cluster-deployment.yaml.j2') | from_yaml }}"
    state: "{{ state }}"
