---
- name: Fetch cluster import secret
  kubernetes.core.k8s_info:
    host: "{{ cluster_api }}"
    api_key: "{{ cluster_api_token }}"
    validate_certs: no
    api_version: v1
    kind: Secret
    name: "{{ item.name }}-import"
    namespace: "{{ item.name }}"
  register: import_secret
  no_log: true

- name: Locate crds.yaml secret
  ansible.builtin.set_fact:
    crds_secret: "{{ import_secret.resources[0].data['crds.yaml'] }}"
  no_log: true

- name: Locate import.yaml secret
  ansible.builtin.set_fact:
    import_secret: "{{ import_secret.resources[0].data['import.yaml'] }}"
  no_log: true

- name: Apply crds and import secret into the cluster
  community.okd.k8s:
    kubeconfig: "{{ item.kubeconfig }}"
    definition: "{{ secret | b64decode }}"
    validate_certs: no
    state: "present"
  loop:
    - "{{ crds_secret }}"
    - "{{ import_secret }}"
  loop_control:
    loop_var: secret
  no_log: true
