---
- name: Set current path
  ansible.builtin.set_fact:
    working_path: "{{ lookup('env', 'PWD') }}"

- name: Validate kubeconfig file existence
  ansible.builtin.stat:
    path: "{{ working_path }}/{{ dir }}/{{ item.name }}/kubeconfig"
  loop: "{{ clusters_dir }}"
  loop_control:
    loop_var: dir
  register: dir_stat

- name: Append kubeconfig path to a cluster entry
  ansible.builtin.set_fact:
    updated_clusters_to_import_list: "{{ updated_clusters_to_import_list | default([])
      + [item | combine({'kubeconfig': (item.kubeconfig | default('')
      + kubeconf_item.stat.path) | trim})] }}"
  loop: "{{ dir_stat.results }}"
  loop_control:
    loop_var: kubeconf_item
  when: kubeconf_item.stat.exists
