---
- name: Uninstall MultiClusterHub
  community.okd.k8s:
    host: "{{ cluster_api }}"
    api_key: "{{ cluster_api_token }}"
    validate_certs: false
    definition: "{{ lookup('template', 'multiclusterhub.yaml.j2') | from_yaml }}"
    state: absent
    wait: true
    wait_timeout: 1200

- name: Delete ACM Subscription
  community.okd.k8s:
    host: "{{ cluster_api }}"
    api_key: "{{ cluster_api_token }}"
    validate_certs: false
    definition: "{{ lookup('template', 'subscription.yaml.j2') | from_yaml }}"
    state: absent
    wait: true
    wait_timeout: 1200

- name: Delete testing configs
  when: deploy_test_env | bool
  block:
    - name: Delete ACM CatalogSource
      community.okd.k8s:
        host: "{{ cluster_api }}"
        api_key: "{{ cluster_api_token }}"
        validate_certs: false
        definition: "{{ lookup('template', 'catalog-source.yaml.j2') | from_yaml }}"
        state: absent
        wait: true
        wait_timeout: 1200
      loop: "{{ catalog_sources }}"

    - name: Delete ImageContentSourcePolicy
      community.okd.k8s:
        host: "{{ cluster_api }}"
        api_key: "{{ cluster_api_token }}"
        validate_certs: false
        definition: "{{ lookup('template', 'image-content-source-policy.yaml.j2') | from_yaml }}"
        state: absent
        wait: true
        wait_timeout: 1200

- name: Delete OperatorGroup
  community.okd.k8s:
    host: "{{ cluster_api }}"
    api_key: "{{ cluster_api_token }}"
    validate_certs: false
    definition: "{{ lookup('template', 'operator-group.yaml.j2') | from_yaml }}"
    state: absent
    wait: true
    wait_timeout: 1200

- name: Delete namespace "{{ acm_namespace }}"
  community.okd.k8s:
    host: "{{ cluster_api }}"
    api_key: "{{ cluster_api_token }}"
    validate_certs: false
    api_version: v1
    kind: Namespace
    name: "{{ acm_namespace }}"
    state: absent
    wait: true
    wait_timeout: 1200
