---
# Set the cluster state of the execution
# The state could be 'present' or 'absent'.
state: present

cluster_api:
cluster_user: kubeadmin
cluster_pass:

# Specify the version in the format of "2.8", "2.7"
acm_version: "2.8"
# Specific snapshot param defined only for testing deployment
snapshot:

acm_namespace: open-cluster-management

# If it's "false", ACM will be deployed from official RH registry
# If it's "true", ACM will be deployed from downstream testing registry
deploy_test_env: false

# For testing deployment only
registry_secrets:
  - name: "quay.io:443"
    user: <username>
    pass: <password>
  - name: "brew.registry.redhat.io"
    user: <username>
    pass: <password>
