---
# Set the cluster state of the execution
# The state could be 'present' or 'absent'.
state: present

cluster_api:
cluster_user: kubeadmin
cluster_pass:

# Specify the version in the format of "2.8", "2.7"
acm_version: "2.8"
# Specific snapshot param defined only for testing deployment
snapshot:

acm_namespace: open-cluster-management

# Define specific acm component and state to override the defaults
# acm_components_overrides:
#   - name: app-lifecycle
#     enabled: true
#   - name: cluster-lifecycle
#     enabled: true
#   - name: cluster-permission
#     enabled: true
#   - name: console
#     enabled: true
#   - name: grc
#     enabled: true
#   - name: insights
#     enabled: true
#   - name: multicluster-engine
#     enabled: true
#   - name: multicluster-observability
#     enabled: true
#   - name: search
#     enabled: false
#   - name: submariner-addon
#     enabled: true
#   - name: volsync
#     enabled: false
#   - name: cluster-backup
#     enabled: true

# If it's "false", ACM will be deployed from official RH registry
# If it's "true", ACM will be deployed from downstream testing registry
deploy_test_env: false

# For testing deployment only
registry_secrets:
  - name: "quay.io:443"
    user: <username>
    pass: <password>
  - name: "brew.registry.redhat.io"
    user: <username>
    pass: <password>
